server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://39.107.240.179:7523
          predicates:
            - Path=/api/** # {map}/{concreteMap} # 通过路径进行匹配

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace


dubbo:
  application:
    name: api-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://39.107.240.179:8848

